#!/bin/bash

# there was soem thing here but i removed it and i dont remember what it is i think it checked if an argument was provided or not

IMAGE="$1"

notify-send "

...changing theme lil bro...

"

swww img "$IMAGE" --transition-type="center" --transition-step=1 --transition-fps="120"

wal -i "$IMAGE"

matugen image "$IMAGE"

pkill waybar
waybar > /dev/null 2>&1 &

