#!/bin/bash

WALL_DIR="$HOME/Wallpapers"

CWD="$(pwd)"

cd "$WALL_DIR" || exit

IFS=$'\n'

SELECTED_WALL=$(for a in *.jpg *.png *.jpeg; do echo -en "$a\0icon\x1f$a\n" ; done | rofi -dmenu -show-icons -p "")

if [ -n "$SELECTED_WALL" ]; then
    walset-backend "$SELECTED_WALL"
fi

cd "$CWD" || exit
